sudo: false
language: clojure
lein: 2.7.1
script: lein with-profile $PROFILE do clean, midje, check
jdk:
  - openjdk7
  - oraclejdk8
env:
  - PROFILE=dev
  - PROFILE=dev,1.8
cache:
  directories:
  - $HOME/.m2
